### ISSUE TITLE
TYPO: alias for mv is "cp -vi"

### ISSUE THREAD

**Issue by raulvasquez** [warbacon/zunder-zsh#18]
https://github.com/warbacon/zunder-zsh/blob/2ce84765a23a1e03490b720c9b8173c67595422f/config/zshrc#L156

The alias to mv files is copying by default.

`alias mv="cp -vi"`

should be 

`alias mv="mv -vi"`

**Comment by warbacon** [comment]
Oops, you're right. I'll fix it right away.

Thank you very much for the contribution, I really appreciate it! :)

**Comment by warbacon** [comment]
Done!
